### 條件1
#### 使用者評論數大於2

In [2]:
import pandas as pd
import os 
import json
df=pd.read_json('./userstar.json',lines=True)
df.head()

,書名,ISBN,words,USER,CONTENT,USERSTAR
0,瞄過一眼就忘不了的世界史：高中老師╳神級YouTuber 2，000萬次點閱的超人氣課程,9789863844433,瞄過一眼忘不世界史高中老師神級 萬次點閱超人氣課程高中老師神級最強圖像記憶法萬次點閱超人氣課...,Frankie,書中先按時期分類，將世界史分開前、中、後三個時期，再將前期世界史按地區分類，令錯綜複雜的大混...,5
1,大戰略：耶魯大學長紅20年大師課程，從歷史提煉的領導決策心法,9789570856712,大戰略耶魯大學長紅年大師課程從歷史提煉領導決策心法金石堂強力推薦書 耶魯大學長紅年戰略大師課...,luckylife8957,這本書花了一點時間才看完，雖然厚度頗高，讀起來卻是趣味十足。\n從一個寓言故事開始破題，然後...,5
2,大戰略：耶魯大學長紅20年大師課程，從歷史提煉的領導決策心法,9789570856712,大戰略耶魯大學長紅年大師課程從歷史提煉領導決策心法金石堂強力推薦書 耶魯大學長紅年戰略大師課...,suliwen,列舉了貫穿古今的戰役歷史，不懂戰略的人來看也是很好看的歷史故事集。,5
3,西方憑什麼：五萬年人類大歷史，破解中國落後之謎,9789868271272,西方憑什麼五萬年人類大歷史破解中國落後之謎 美國筆會書獎德國國際財經書獎 美國英國中國德國暢...,p26842082001,古早決定論 vs. 一時碰巧論,3
4,西方憑什麼：五萬年人類大歷史，破解中國落後之謎,9789868271272,西方憑什麼五萬年人類大歷史破解中國落後之謎 美國筆會書獎德國國際財經書獎 美國英國中國德國暢...,rex.mcchiu,東西方比對發展軌跡的論述，清晰、具說服力時之所需支撐社會發展方向+地理決定論,5

In [4]:
df=df.dropna(axis=0)  # 刪除空值

In [5]:
df=df.drop(df[df["ISBN"]=='0'].index,axis=0)   # 刪除 ISBN等於 0

In [5]:
#df.loc[df['USERSTAR']==0,'USERSTAR']=float(1.0)    # 評分為 0 分給予 1 分

In [6]:
df['ISBN'] = df['ISBN'].astype('str')  # 確認 ISBN 為 STR
df['USERSTAR'] = df['USERSTAR'].astype('float64')  # 確認USERSTAR 為 float64

In [7]:
df_star=df
df_star

,書名,ISBN,words,USER,CONTENT,USERSTAR
0,瞄過一眼就忘不了的世界史：高中老師╳神級YouTuber 2，000萬次點閱的超人氣課程,9789863844433,瞄過一眼忘不世界史高中老師神級 萬次點閱超人氣課程高中老師神級最強圖像記憶法萬次點閱超人氣課...,Frankie,書中先按時期分類，將世界史分開前、中、後三個時期，再將前期世界史按地區分類，令錯綜複雜的大混...,5.0
1,大戰略：耶魯大學長紅20年大師課程，從歷史提煉的領導決策心法,9789570856712,大戰略耶魯大學長紅年大師課程從歷史提煉領導決策心法金石堂強力推薦書 耶魯大學長紅年戰略大師課...,luckylife8957,這本書花了一點時間才看完，雖然厚度頗高，讀起來卻是趣味十足。\n從一個寓言故事開始破題，然後...,5.0
2,大戰略：耶魯大學長紅20年大師課程，從歷史提煉的領導決策心法,9789570856712,大戰略耶魯大學長紅年大師課程從歷史提煉領導決策心法金石堂強力推薦書 耶魯大學長紅年戰略大師課...,suliwen,列舉了貫穿古今的戰役歷史，不懂戰略的人來看也是很好看的歷史故事集。,5.0
3,西方憑什麼：五萬年人類大歷史，破解中國落後之謎,9789868271272,西方憑什麼五萬年人類大歷史破解中國落後之謎 美國筆會書獎德國國際財經書獎 美國英國中國德國暢...,p26842082001,古早決定論 vs. 一時碰巧論,3.0
4,西方憑什麼：五萬年人類大歷史，破解中國落後之謎,9789868271272,西方憑什麼五萬年人類大歷史破解中國落後之謎 美國筆會書獎德國國際財經書獎 美國英國中國德國暢...,rex.mcchiu,東西方比對發展軌跡的論述，清晰、具說服力時之所需支撐社會發展方向+地理決定論,5.0
...,...,...,...,...,...,...
57636,城市獵人35,9789571305943,城市獵人作者簡介北條司 年 月 生本福剛縣人 年投稿第 屆手塚賞為尊崇本漫畫大師手塚治...,萌太,翻一翻城市獵人出版日期，1985，僅僅比我小一歲。在那個年代裡，相信這樣畫風精緻、兼具戰鬥跟...,3.0
57637,怪奇檔案全,9789573464747,怪奇檔案全恐怖漫畫界巨匠野出志早期留下短篇４篇以被譽為最佳傑作藏六怪病開始每一篇扣人心弦非常...,fevlaner,市面僅見的日野日出志作品\n也是第一本接觸，卻驚為天人的精選集\n日野日出志的作品風格不一\...,5.0
57638,阿保的童話,9789576930041,阿保童話如詩般阿保漫畫像夢般童年寄情歲孩童珍寶也成年人心中精靈每故事輕易帶領夢一般美麗天空中...,凜,〈炎夏裡的綿綿雪花〉是我的最愛。,5.0
57639,小鎮人家,9789576930058,小鎮人家阿保美代漫畫有散文氣質且精簡哲理散文觀賞小鎮人家有如閱讀莊子書中寓言故事蒲公英訊息中...,凜,純真。,5.0
57640,森林小語,9789576930072,森林小語中國人常說詩中有畫畫中有詩森林小語正這一句話最好詮釋文字用得輕巧懂得中國話中留白趣味...,凜,溫柔的童話。,5.0

In [8]:
#評論數大於2 抓出
df_star=df_star.groupby('USER').filter(lambda x : len(x)>1)
df_star=df_star.reset_index(drop=True)

In [9]:
df_star['user_id'] = pd.Categorical(df_star.USER).codes

In [10]:
df_star=df_star.sort_values(by=['user_id']) # 為使用者上ID
df_star

,書名,ISBN,words,USER,CONTENT,USERSTAR,user_id
28194,陳澄波密碼,9789573283928,陳澄波密碼第三屆台灣歷史小說獎首獎作品畫作充滿謎團名字不能說祕密為什麼畫作上簽名不見為什麼畫...,Lily,有趣的作品，透過發現畫作不自然之處然後追尋、解謎的過程讓人想起達文西密碼。看完小說會想再找時...,4.0,0
1275,中華秩序：中原、世界帝國，與中國力量的本質,9789578654365,中華秩序中原世界帝國中國力量本質為什麼中華人民共國許叫秦漢人民共國才更恰當用中華夢馬克思主義...,Lily,本書從地理（與主要是）歷史角度分析中國/中華秩序的本質，以及中華秩序對世界的影響（與/或危害...,5.0,0
2943,深入最禁忌的消化道之旅,9789864798056,深入最禁忌消化道之旅美國最有趣科普作家瑪莉羅曲最膾炙人口作紐約時報非文學暢銷書排行榜第二名盤...,Lily,非常有趣的一本書，作者幽默風趣的筆法令人捧腹大笑\n看完這本跟NASA那本書以後，我確定了以...,5.0,0
3422,噢！原來如此有趣的鳥類學,9789864086368,噢原來如此有趣鳥類學噢噢原來牠們還會這樣啊從今之後想再多解鳥類一點 簡介 從獸腳類恐龍開始演...,Lily,鳥類學入門不可錯過的一本書！\n插畫可愛又傳神，搭配淺顯易懂的文字和有趣的舉例，每篇篇幅差不...,5.0,0
45109,不能贏的辯護【艾迪．弗林系列1】,9789865509125,不能贏辯護艾迪弗林系列英國犯罪作家學會金匕首獎得主史蒂夫卡瓦納打破格局燒腦神作史上最囂張騙子...,-3-,一句話感想：看完我已經直接買下後續2本系列作了XD \n\n很精彩的法庭推理驚悚小說，看了真...,5.0,1
...,...,...,...,...,...,...,...
26424,想見你Someday or One Day原著小說,9789869811750,想見你 原小說柯佳嬿許光漢施柏宇等人氣演員主演因為走不出對已逝男友王詮勝思念黃雨萱試圖用...,＜＞＜,這個故事的題材很特別，融合推理、愛情、平行時空等元素。\n\n故事的緣起是因為黃雨萱太想見到...,5.0,3764
45004,亞森．羅蘋冒險系列5：怪盜與名偵探,9789861781716,亞森羅蘋冒險系列怪盜名偵探亞森羅蘋福爾摩斯對決法文原版一字不漏譯本完整呈現羅蘋冒險世界亞馬遜...,＜＞＜,不得不說莫里斯早期的角色個性設定真的很討人厭，書中的福爾摩斯只是一個空有虛名、自以為是的草包...,3.0,3764
4229,真相製造：從聖戰士媽媽、極權政府、網軍教練、境外勢力、打假部隊、內容農場主人到政府小編,9789860659788,真相製造從聖戰士媽媽極權政府網軍教練境外勢力打假部隊內容農場主人到政府小編金鼎獎卓越新聞獎人...,＜＞＜,❝事實無人聞問。\n\n在這個資訊取得太過於容易的時代，人們反而失去了追求真相的動力，沉溺於...,5.0,3764
25241,台味便當：30個便當提案X 46種家常配菜X 15道私房好味道,9789863616894,台味便當個便當提案 種家常配菜 道私房好味道誰說台味只能台灣小吃傳統台菜 有一種台味出現於自...,＜＞＜,趁著這次料理馬拉松，仔細地翻閱了這本食譜，但說它是食譜其實又不只教了料理作法，每一道菜都配著...,5.0,3764
11881,有一間咖啡廳（典藏版）,9789866277702,有一間咖啡廳典藏版海洋裡一隻隻熱帶魚鮮豔但體溫即使相擁也體溫隔兩重玻璃互望氣泡聲音讓寂靜更寂...,＜＞＜,蝶大早期的書我真是水土不服～\n\n書中一直沒有交代女主角沈靜的背景與過往經歷，因此讓我很難...,3.0,3764

In [11]:
df_starpivot = df_star.pivot_table(index='user_id', columns='ISBN', values='USERSTAR')
df_starpivot

ISBN,1509092070025,1611172070020,1706192070010,2006172050018,2020070100002,4710415380562,4710415381385,4710415381392,4710415381453,4710415382450,...,9789888481248,9789888490813,9789888599233,9789889841027,9789889964740,9799577623200,9799577623224,9991070427013,9991080725031,9999000914138
user_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_newpivot= df_starpivot.fillna(float(0))  # 空值補 0

In [13]:
to_array=df_newpivot.values   # 轉成向量
to_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
users=df_newpivot.index.astype('int').max()   # 轉型別
userid=[i for i in range(users+1)]

In [15]:
from sklearn.metrics.pairwise import cosine_similarity   # 餘絃相似度
cos_sims = cosine_similarity(to_array)
sims_df=pd.DataFrame(cos_sims,columns=userid,index=userid)
sims_df

,0,1,2,3,4,5,6,7,8,9,...,3755,3756,3757,3758,3759,3760,3761,3762,3763,3764
0,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.066566,0.0,0.0,0.0,0.0
2,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3760,0.0,0.066566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.031089,0.0,0.0,1.000000,0.0,0.0,0.0,0.0
3761,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,1.0,0.0,0.0,0.0
3762,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,1.0,0.0,0.0
3763,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,1.0,0.0
3764,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,1.0

## 兩使用者所看的書

In [16]:
sims_df.iloc[:,33].nlargest(2) # userid=33 的使用者 相似前兩名 第一為自己

33    1.0
0     0.0
Name: 33, dtype: float64

In [17]:
df_star.loc[df_star['user_id']==33][:] # 自己看過的書

,BOOKNAME,CONTENT,ISBN,USER,USERSTAR,user_id
66813,TOO BIG TO KNOW,"在網路發達資訊爆炸的年代，過去傳統的知識傳遞與架構正經歷翻天覆地的改變,\n有的人預言這將造...",9789862622025,97252013,5.0,33
66792,"無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代",作者用了許多大家評論或敘述文學藝術哲學之存在價值，讓讀者去反思在現代社會中所崇尚經濟邏輯下的...,9789865671723,97252013,4.0,33
66810,從0到1,打破一般傳統工業邏輯思維，不強調快速複製的技術，只追求能夠打破世界秩序與市場需求的破壞式創新...,9789862419533,97252013,4.0,33
66811,人類大歷史,歷史敘述結合哲學、經濟學已經不稀奇了，但本書除此之外更從人類學、考古學、科技史學等角度進行切...,9789863205449,97252013,5.0,33
66803,異鄉人,在喧囂的人群佇足，或許可以假裝自己是個社會化成熟的大人\n看著群眾此起彼落的攻訐，仔細聆聽試...,9789861735450,97252013,4.0,33

In [18]:
df_star.loc[df_star['user_id']==1516][:] # 對方看過的書

,BOOKNAME,CONTENT,ISBN,USER,USERSTAR,user_id
20243,麒麟之翼,一如過往的加賀恭一郎系列，在尋找凶案真相過程中，扣連到疏離的家庭，嗜血的媒體，派遣人員的不公...,9789866043345,evava,4.0,1516
32205,起源,丹．布朗的羅柏·蘭登系列所探討的題材每每有驚喜，這次也不例外，選取了具爭議性的題材──人類的...,9789571373867,evava,5.0,1516

In [19]:
sims_df.iloc[:,5].nlargest(5).index # user_id = 5 相似的前五名  第一名為自己

Int64Index([5, 4039, 481, 565, 665], dtype='int64')

In [20]:
df_star.loc[df_star.user_id==5]['BOOKNAME'] # user_id = 5 看的書

8437            關係黑洞：面對侵蝕關係的不安全感，我們該如何救贖自己？
8441                      兩個女人住一起：非關愛情的同居時代
16356                                 女神自助餐
15764                          致不在場的他們與遲到的我
15655                         李智雅姊姊，現在終於能說了
15649               破碎之海Ⅰ：半王的復仇 Half a King
15646                                我們沒有祕密
15645    燈塔行（吳爾芙經典傳世之作，出版91周年雙面海報燙銀書衣典藏紀念版）
15642                          破碎之海Ⅱ：劍魂的試煉
15531                                 莫斯科紳士
15529                                  如膚之深
15516                           破碎之海Ⅲ：權力的灰燼
15421                               明天別再來敲門
9485                     過度努力：每個「過度」，都是傷的證明
Name: BOOKNAME, dtype: object

In [21]:
df_star.loc[df_star.user_id==3962]['BOOKNAME'] # user_id= 3962 看的書 * 發現都看過莫斯科的紳士這本書

10097                  半澤喵樹(01)
12347                      蟲師 1
13153                     午夜圖書館
8361                         邪臨
9067          一不小心就和魔法師契約結婚了（1）
                  ...
16787                     傲慢與善良
12017                     大港的女兒
63787            爸爸與父親的家庭食堂(03)
16785    Dr. Dmat ~ 瓦礫下的醫師 ~(1)
53552                      誰殺了她
Name: BOOKNAME, Length: 226, dtype: object

In [22]:
sims_df.iloc[:,33].nlargest(4)  # user_id 33 和 1516 相似度接近一

33      1.000000
3204    0.505076
1250    0.433099
3233    0.433099
Name: 33, dtype: float64

In [23]:
# 取出 user_id 和 similarity 做成 list
sim_scores=list(sims_df.iloc[:,33].nlargest(5))
# 與 user_id 與 其他使用者的相似度
sim_users=list(sims_df.iloc[:,33].nlargest(5).index)
print(sim_users)
sim_scores

[33, 3204, 1250, 3233, 3073]

[1.0000000000000002,
 0.5050762722761054,
 0.43309933042202314,
 0.43309933042202314,
 0.3943983074101663]

In [24]:
# 丟入dictionary
sims_dict={}
for i in range(1,5):
    sims_dict[str(sim_users[i])]=sim_scores[i]
print(sims_dict)

{'3204': 0.5050762722761054, '1250': 0.43309933042202314, '3233': 0.43309933042202314, '3073': 0.3943983074101663}

In [25]:
# 比對差集(雙方沒有交集的書籍) 減 自己看過的書 = 對方和自己沒交集的書
own=list(df_star.loc[df_star.user_id==33]['BOOKNAME'])
print(own)
for k,v in sims_dict.items():
    the_other=list(df_star.loc[df_star.user_id==int(k)]['BOOKNAME'])
    print(f'還可以看{set(the_other)-set(own)}，讀者{k}相似度{v:.2f}')
    print()

['TOO BIG TO KNOW', '無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代', '從0到1', '人類大歷史', '異鄉人']
還可以看{'一流的人讀書，都在哪裡畫線？'}，讀者3204相似度0.51

還可以看{'文明更迭的源代碼'}，讀者1250相似度0.43

還可以看{'正妹心理學'}，讀者3233相似度0.43

還可以看{'惡血'}，讀者3073相似度0.39

In [26]:
# 做出 丟入 user_id 的號碼 ， 抓出前五大similartiy 沒有看過的書
userid=1

while userid!='':
    userid=input('enter userid:(print enter to end) ')
    if userid=='':
        break
    userid=int(userid)
    make_sure=list(sims_df.iloc[:,userid].nlargest(5).index)
    x=make_sure[0]
    y=make_sure[1]
    print('相似使用者:',y)
    own=list(df_star.loc[df_star.user_id==x]['BOOKNAME'])
    print(f'{x}看了{own}')
    the_other=list(df_star.loc[df_star.user_id==y]['BOOKNAME'])
    print(f'{y}看了{the_other}')
    book_n=0
    book_un=0
    for i in own:
        if i in the_other:
            book_n+=1
            print(i,'相同')
    print('共相同:',book_n,'本書')
    print('還可以看:',set(own) ^ set(the_other))

enter userid:(print enter to end) 33
相似使用者: 3204
33看了['TOO BIG TO KNOW', '無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代', '從0到1', '人類大歷史', '異鄉人']
3204看了['一流的人讀書，都在哪裡畫線？', '人類大歷史']
人類大歷史 相同
共相同: 1 本書
還可以看: {'TOO BIG TO KNOW', '無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代', '一流的人讀書，都在哪裡畫線？', '異鄉人', '從0到1'}
enter userid:(print enter to end)

## 後缺: 
+ 類別推書(K-means)
+ 列出分數較高的書籍(coding)
+ 預測使用者給的分數(knn?)